# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27e175bced91972f9aa535ec27e895121b5557a6e494e0c8399170754792d79fc757388e4f1053297f8101d167ad06da7fd06b25072ac003c9779f536dc1b138

test:
  secret_key_base: dbb6a17bd5fb61ae2beeb947cba6ef916d212a2730d5cf13febce268d031cab46a27acfe145add60837991597800a6f00026eed90f7b9fe748741b49341a02fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
